<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    '5b3631295f068108506cdbdbb145341f' => $vendorDir . '/ssnepenthe/color-utils/inc/colors.php',
    'cab4a6b55e27af8a3962c88e0096abd8' => $vendorDir . '/ssnepenthe/color-utils/inc/helpers.php',
    'cde4be3408200b8d3bb84af05ef4e338' => $vendorDir . '/ssnepenthe/color-utils/inc/transformations.php',
);
