<?php

// autoload_real.php @generated by Composer

class ComposerAutoloaderInit6c6a2616474ca43a7e544b9ba321cd2b
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('LearnDash\Gradebook\Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \LearnDash\Gradebook\Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        require __DIR__ . '/platform_check.php';

        spl_autoload_register(array('ComposerAutoloaderInit6c6a2616474ca43a7e544b9ba321cd2b', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \LearnDash\Gradebook\Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('ComposerAutoloaderInit6c6a2616474ca43a7e544b9ba321cd2b', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        call_user_func(\LearnDash\Gradebook\Composer\Autoload\ComposerStaticInit6c6a2616474ca43a7e544b9ba321cd2b::getInitializer($loader));

        $loader->setClassMapAuthoritative(true);
        $loader->register(true);

        $filesToLoad = \LearnDash\Gradebook\Composer\Autoload\ComposerStaticInit6c6a2616474ca43a7e544b9ba321cd2b::$files;
        $requireFile = \Closure::bind(static function ($fileIdentifier, $file) {
            if (empty($GLOBALS['__composer_autoload_files'][$fileIdentifier])) {
                $GLOBALS['__composer_autoload_files'][$fileIdentifier] = true;

                require $file;
            }
        }, null, null);
        foreach ($filesToLoad as $fileIdentifier => $file) {
            $requireFile($fileIdentifier, $file);
        }

        return $loader;
    }
}
