<?php

// autoload_static.php @generated by Composer

namespace LearnDash\Gradebook\Composer\Autoload;

class ComposerStaticInit6c6a2616474ca43a7e544b9ba321cd2b
{
    public static $files = array (
        '5b3631295f068108506cdbdbb145341f' => __DIR__ . '/..' . '/ssnepenthe/color-utils/inc/colors.php',
        'cab4a6b55e27af8a3962c88e0096abd8' => __DIR__ . '/..' . '/ssnepenthe/color-utils/inc/helpers.php',
        'cde4be3408200b8d3bb84af05ef4e338' => __DIR__ . '/..' . '/ssnepenthe/color-utils/inc/transformations.php',
    );

    public static $prefixLengthsPsr4 = array (
        'L' =>
        array (
            'LearnDash\\Gradebook\\WPTRT\\AdminNotices\\' => 39,
            'LearnDash\\Gradebook\\SSNepenthe\\ColorUtils\\' => 42,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'LearnDash\\Gradebook\\WPTRT\\AdminNotices\\' =>
        array (
            0 => __DIR__ . '/..' . '/wptrt/admin-notices/src',
        ),
        'LearnDash\\Gradebook\\SSNepenthe\\ColorUtils\\' =>
        array (
            0 => __DIR__ . '/..' . '/ssnepenthe/color-utils/src',
        ),
    );

    public static $classMap = array (
        'LearnDash\\Gradebook\\Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'LearnDash\\Gradebook\\SSNepenthe\\ColorUtils\\Colors\\BaseColor' => __DIR__ . '/..' . '/ssnepenthe/color-utils/src/Colors/BaseColor.php',
        'LearnDash\\Gradebook\\SSNepenthe\\ColorUtils\\Colors\\Color' => __DIR__ . '/..' . '/ssnepenthe/color-utils/src/Colors/Color.php',
        'LearnDash\\Gradebook\\SSNepenthe\\ColorUtils\\Colors\\ColorFactory' => __DIR__ . '/..' . '/ssnepenthe/color-utils/src/Colors/ColorFactory.php',
        'LearnDash\\Gradebook\\SSNepenthe\\ColorUtils\\Colors\\ColorInterface' => __DIR__ . '/..' . '/ssnepenthe/color-utils/src/Colors/ColorInterface.php',
        'LearnDash\\Gradebook\\SSNepenthe\\ColorUtils\\Colors\\Hsl' => __DIR__ . '/..' . '/ssnepenthe/color-utils/src/Colors/Hsl.php',
        'LearnDash\\Gradebook\\SSNepenthe\\ColorUtils\\Colors\\Hsla' => __DIR__ . '/..' . '/ssnepenthe/color-utils/src/Colors/Hsla.php',
        'LearnDash\\Gradebook\\SSNepenthe\\ColorUtils\\Colors\\Rgb' => __DIR__ . '/..' . '/ssnepenthe/color-utils/src/Colors/Rgb.php',
        'LearnDash\\Gradebook\\SSNepenthe\\ColorUtils\\Colors\\Rgba' => __DIR__ . '/..' . '/ssnepenthe/color-utils/src/Colors/Rgba.php',
        'LearnDash\\Gradebook\\SSNepenthe\\ColorUtils\\Converters\\ConverterInterface' => __DIR__ . '/..' . '/ssnepenthe/color-utils/src/Converters/ConverterInterface.php',
        'LearnDash\\Gradebook\\SSNepenthe\\ColorUtils\\Converters\\HslToRgb' => __DIR__ . '/..' . '/ssnepenthe/color-utils/src/Converters/HslToRgb.php',
        'LearnDash\\Gradebook\\SSNepenthe\\ColorUtils\\Converters\\RgbToHsl' => __DIR__ . '/..' . '/ssnepenthe/color-utils/src/Converters/RgbToHsl.php',
        'LearnDash\\Gradebook\\SSNepenthe\\ColorUtils\\Exceptions\\BadMethodCallException' => __DIR__ . '/..' . '/ssnepenthe/color-utils/src/Exceptions/BadMethodCallException.php',
        'LearnDash\\Gradebook\\SSNepenthe\\ColorUtils\\Exceptions\\ExceptionInterface' => __DIR__ . '/..' . '/ssnepenthe/color-utils/src/Exceptions/ExceptionInterface.php',
        'LearnDash\\Gradebook\\SSNepenthe\\ColorUtils\\Exceptions\\InvalidArgumentException' => __DIR__ . '/..' . '/ssnepenthe/color-utils/src/Exceptions/InvalidArgumentException.php',
        'LearnDash\\Gradebook\\SSNepenthe\\ColorUtils\\Exceptions\\LogicException' => __DIR__ . '/..' . '/ssnepenthe/color-utils/src/Exceptions/LogicException.php',
        'LearnDash\\Gradebook\\SSNepenthe\\ColorUtils\\Exceptions\\RuntimeException' => __DIR__ . '/..' . '/ssnepenthe/color-utils/src/Exceptions/RuntimeException.php',
        'LearnDash\\Gradebook\\SSNepenthe\\ColorUtils\\Parsers\\DelegatingParser' => __DIR__ . '/..' . '/ssnepenthe/color-utils/src/Parsers/DelegatingParser.php',
        'LearnDash\\Gradebook\\SSNepenthe\\ColorUtils\\Parsers\\HexParser' => __DIR__ . '/..' . '/ssnepenthe/color-utils/src/Parsers/HexParser.php',
        'LearnDash\\Gradebook\\SSNepenthe\\ColorUtils\\Parsers\\HslParser' => __DIR__ . '/..' . '/ssnepenthe/color-utils/src/Parsers/HslParser.php',
        'LearnDash\\Gradebook\\SSNepenthe\\ColorUtils\\Parsers\\HslaParser' => __DIR__ . '/..' . '/ssnepenthe/color-utils/src/Parsers/HslaParser.php',
        'LearnDash\\Gradebook\\SSNepenthe\\ColorUtils\\Parsers\\KeywordParser' => __DIR__ . '/..' . '/ssnepenthe/color-utils/src/Parsers/KeywordParser.php',
        'LearnDash\\Gradebook\\SSNepenthe\\ColorUtils\\Parsers\\ParserInterface' => __DIR__ . '/..' . '/ssnepenthe/color-utils/src/Parsers/ParserInterface.php',
        'LearnDash\\Gradebook\\SSNepenthe\\ColorUtils\\Parsers\\ParserResolver' => __DIR__ . '/..' . '/ssnepenthe/color-utils/src/Parsers/ParserResolver.php',
        'LearnDash\\Gradebook\\SSNepenthe\\ColorUtils\\Parsers\\ParserResolverFactory' => __DIR__ . '/..' . '/ssnepenthe/color-utils/src/Parsers/ParserResolverFactory.php',
        'LearnDash\\Gradebook\\SSNepenthe\\ColorUtils\\Parsers\\ParserResolverInterface' => __DIR__ . '/..' . '/ssnepenthe/color-utils/src/Parsers/ParserResolverInterface.php',
        'LearnDash\\Gradebook\\SSNepenthe\\ColorUtils\\Parsers\\PatternParser' => __DIR__ . '/..' . '/ssnepenthe/color-utils/src/Parsers/PatternParser.php',
        'LearnDash\\Gradebook\\SSNepenthe\\ColorUtils\\Parsers\\RgbParser' => __DIR__ . '/..' . '/ssnepenthe/color-utils/src/Parsers/RgbParser.php',
        'LearnDash\\Gradebook\\SSNepenthe\\ColorUtils\\Parsers\\RgbaParser' => __DIR__ . '/..' . '/ssnepenthe/color-utils/src/Parsers/RgbaParser.php',
        'LearnDash\\Gradebook\\SSNepenthe\\ColorUtils\\Transformers\\AdjustColor' => __DIR__ . '/..' . '/ssnepenthe/color-utils/src/Transformers/AdjustColor.php',
        'LearnDash\\Gradebook\\SSNepenthe\\ColorUtils\\Transformers\\AdjustHue' => __DIR__ . '/..' . '/ssnepenthe/color-utils/src/Transformers/AdjustHue.php',
        'LearnDash\\Gradebook\\SSNepenthe\\ColorUtils\\Transformers\\ChangeColor' => __DIR__ . '/..' . '/ssnepenthe/color-utils/src/Transformers/ChangeColor.php',
        'LearnDash\\Gradebook\\SSNepenthe\\ColorUtils\\Transformers\\Complement' => __DIR__ . '/..' . '/ssnepenthe/color-utils/src/Transformers/Complement.php',
        'LearnDash\\Gradebook\\SSNepenthe\\ColorUtils\\Transformers\\ConditionalTransformer' => __DIR__ . '/..' . '/ssnepenthe/color-utils/src/Transformers/ConditionalTransformer.php',
        'LearnDash\\Gradebook\\SSNepenthe\\ColorUtils\\Transformers\\Darken' => __DIR__ . '/..' . '/ssnepenthe/color-utils/src/Transformers/Darken.php',
        'LearnDash\\Gradebook\\SSNepenthe\\ColorUtils\\Transformers\\Desaturate' => __DIR__ . '/..' . '/ssnepenthe/color-utils/src/Transformers/Desaturate.php',
        'LearnDash\\Gradebook\\SSNepenthe\\ColorUtils\\Transformers\\GrayScale' => __DIR__ . '/..' . '/ssnepenthe/color-utils/src/Transformers/GrayScale.php',
        'LearnDash\\Gradebook\\SSNepenthe\\ColorUtils\\Transformers\\Invert' => __DIR__ . '/..' . '/ssnepenthe/color-utils/src/Transformers/Invert.php',
        'LearnDash\\Gradebook\\SSNepenthe\\ColorUtils\\Transformers\\Lighten' => __DIR__ . '/..' . '/ssnepenthe/color-utils/src/Transformers/Lighten.php',
        'LearnDash\\Gradebook\\SSNepenthe\\ColorUtils\\Transformers\\Mix' => __DIR__ . '/..' . '/ssnepenthe/color-utils/src/Transformers/Mix.php',
        'LearnDash\\Gradebook\\SSNepenthe\\ColorUtils\\Transformers\\Opacify' => __DIR__ . '/..' . '/ssnepenthe/color-utils/src/Transformers/Opacify.php',
        'LearnDash\\Gradebook\\SSNepenthe\\ColorUtils\\Transformers\\Saturate' => __DIR__ . '/..' . '/ssnepenthe/color-utils/src/Transformers/Saturate.php',
        'LearnDash\\Gradebook\\SSNepenthe\\ColorUtils\\Transformers\\ScaleColor' => __DIR__ . '/..' . '/ssnepenthe/color-utils/src/Transformers/ScaleColor.php',
        'LearnDash\\Gradebook\\SSNepenthe\\ColorUtils\\Transformers\\Shade' => __DIR__ . '/..' . '/ssnepenthe/color-utils/src/Transformers/Shade.php',
        'LearnDash\\Gradebook\\SSNepenthe\\ColorUtils\\Transformers\\Tint' => __DIR__ . '/..' . '/ssnepenthe/color-utils/src/Transformers/Tint.php',
        'LearnDash\\Gradebook\\SSNepenthe\\ColorUtils\\Transformers\\TransformerInterface' => __DIR__ . '/..' . '/ssnepenthe/color-utils/src/Transformers/TransformerInterface.php',
        'LearnDash\\Gradebook\\SSNepenthe\\ColorUtils\\Transformers\\TransformerPipeline' => __DIR__ . '/..' . '/ssnepenthe/color-utils/src/Transformers/TransformerPipeline.php',
        'LearnDash\\Gradebook\\SSNepenthe\\ColorUtils\\Transformers\\Transparentize' => __DIR__ . '/..' . '/ssnepenthe/color-utils/src/Transformers/Transparentize.php',
        'LearnDash\\Gradebook\\WPTRT\\AdminNotices\\Dismiss' => __DIR__ . '/..' . '/wptrt/admin-notices/src/Dismiss.php',
        'LearnDash\\Gradebook\\WPTRT\\AdminNotices\\Notice' => __DIR__ . '/..' . '/wptrt/admin-notices/src/Notice.php',
        'LearnDash\\Gradebook\\WPTRT\\AdminNotices\\Notices' => __DIR__ . '/..' . '/wptrt/admin-notices/src/Notices.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit6c6a2616474ca43a7e544b9ba321cd2b::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit6c6a2616474ca43a7e544b9ba321cd2b::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit6c6a2616474ca43a7e544b9ba321cd2b::$classMap;

        }, null, ClassLoader::class);
    }
}
