<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'LearnDash\\Gradebook\\WPTRT\\AdminNotices\\' => array($vendorDir . '/wptrt/admin-notices/src'),
    'LearnDash\\Gradebook\\SSNepenthe\\ColorUtils\\' => array($vendorDir . '/ssnepenthe/color-utils/src'),
);
