<?php

// autoload_static.php @generated by Composer

namespace LearnDash\Instructor_Role\Composer\Autoload;

class ComposerStaticInit5b3b406b0c8b093372f4de300008eb3b
{
    public static $prefixLengthsPsr4 = array (
        'L' =>
        array (
            'LearnDash\\Instructor_Role\\StellarWP\\DB\\' => 39,
            'LearnDash\\Instructor_Role\\StellarWP\\Assets\\' => 43,
            'LearnDash\\Instructor_Role\\StellarWP\\Arrays\\' => 43,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'LearnDash\\Instructor_Role\\StellarWP\\DB\\' =>
        array (
            0 => __DIR__ . '/..' . '/stellarwp/db/src/DB',
        ),
        'LearnDash\\Instructor_Role\\StellarWP\\Assets\\' =>
        array (
            0 => __DIR__ . '/..' . '/stellarwp/assets/src/Assets',
        ),
        'LearnDash\\Instructor_Role\\StellarWP\\Arrays\\' =>
        array (
            0 => __DIR__ . '/..' . '/stellarwp/arrays/src/Arrays',
        ),
    );

    public static $classMap = array (
        'LearnDash\\Instructor_Role\\Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'LearnDash\\Instructor_Role\\StellarWP\\Arrays\\Arr' => __DIR__ . '/..' . '/stellarwp/arrays/src/Arrays/Arr.php',
        'LearnDash\\Instructor_Role\\StellarWP\\Assets\\Asset' => __DIR__ . '/..' . '/stellarwp/assets/src/Assets/Asset.php',
        'LearnDash\\Instructor_Role\\StellarWP\\Assets\\Assets' => __DIR__ . '/..' . '/stellarwp/assets/src/Assets/Assets.php',
        'LearnDash\\Instructor_Role\\StellarWP\\Assets\\Config' => __DIR__ . '/..' . '/stellarwp/assets/src/Assets/Config.php',
        'LearnDash\\Instructor_Role\\StellarWP\\Assets\\Controller' => __DIR__ . '/..' . '/stellarwp/assets/src/Assets/Controller.php',
        'LearnDash\\Instructor_Role\\StellarWP\\Assets\\Data' => __DIR__ . '/..' . '/stellarwp/assets/src/Assets/Data.php',
        'LearnDash\\Instructor_Role\\StellarWP\\Assets\\Utils' => __DIR__ . '/..' . '/stellarwp/assets/src/Assets/Utils.php',
        'LearnDash\\Instructor_Role\\StellarWP\\DB\\Config' => __DIR__ . '/..' . '/stellarwp/db/src/DB/Config.php',
        'LearnDash\\Instructor_Role\\StellarWP\\DB\\DB' => __DIR__ . '/..' . '/stellarwp/db/src/DB/DB.php',
        'LearnDash\\Instructor_Role\\StellarWP\\DB\\Database\\Actions\\EnableBigSqlSelects' => __DIR__ . '/..' . '/stellarwp/db/src/DB/Database/Actions/EnableBigSqlSelects.php',
        'LearnDash\\Instructor_Role\\StellarWP\\DB\\Database\\Exceptions\\DatabaseQueryException' => __DIR__ . '/..' . '/stellarwp/db/src/DB/Database/Exceptions/DatabaseQueryException.php',
        'LearnDash\\Instructor_Role\\StellarWP\\DB\\Database\\Provider' => __DIR__ . '/..' . '/stellarwp/db/src/DB/Database/Provider.php',
        'LearnDash\\Instructor_Role\\StellarWP\\DB\\QueryBuilder\\Clauses\\From' => __DIR__ . '/..' . '/stellarwp/db/src/DB/QueryBuilder/Clauses/From.php',
        'LearnDash\\Instructor_Role\\StellarWP\\DB\\QueryBuilder\\Clauses\\Having' => __DIR__ . '/..' . '/stellarwp/db/src/DB/QueryBuilder/Clauses/Having.php',
        'LearnDash\\Instructor_Role\\StellarWP\\DB\\QueryBuilder\\Clauses\\Join' => __DIR__ . '/..' . '/stellarwp/db/src/DB/QueryBuilder/Clauses/Join.php',
        'LearnDash\\Instructor_Role\\StellarWP\\DB\\QueryBuilder\\Clauses\\JoinCondition' => __DIR__ . '/..' . '/stellarwp/db/src/DB/QueryBuilder/Clauses/JoinCondition.php',
        'LearnDash\\Instructor_Role\\StellarWP\\DB\\QueryBuilder\\Clauses\\MetaTable' => __DIR__ . '/..' . '/stellarwp/db/src/DB/QueryBuilder/Clauses/MetaTable.php',
        'LearnDash\\Instructor_Role\\StellarWP\\DB\\QueryBuilder\\Clauses\\OrderBy' => __DIR__ . '/..' . '/stellarwp/db/src/DB/QueryBuilder/Clauses/OrderBy.php',
        'LearnDash\\Instructor_Role\\StellarWP\\DB\\QueryBuilder\\Clauses\\RawSQL' => __DIR__ . '/..' . '/stellarwp/db/src/DB/QueryBuilder/Clauses/RawSQL.php',
        'LearnDash\\Instructor_Role\\StellarWP\\DB\\QueryBuilder\\Clauses\\Select' => __DIR__ . '/..' . '/stellarwp/db/src/DB/QueryBuilder/Clauses/Select.php',
        'LearnDash\\Instructor_Role\\StellarWP\\DB\\QueryBuilder\\Clauses\\Union' => __DIR__ . '/..' . '/stellarwp/db/src/DB/QueryBuilder/Clauses/Union.php',
        'LearnDash\\Instructor_Role\\StellarWP\\DB\\QueryBuilder\\Clauses\\Where' => __DIR__ . '/..' . '/stellarwp/db/src/DB/QueryBuilder/Clauses/Where.php',
        'LearnDash\\Instructor_Role\\StellarWP\\DB\\QueryBuilder\\Concerns\\Aggregate' => __DIR__ . '/..' . '/stellarwp/db/src/DB/QueryBuilder/Concerns/Aggregate.php',
        'LearnDash\\Instructor_Role\\StellarWP\\DB\\QueryBuilder\\Concerns\\CRUD' => __DIR__ . '/..' . '/stellarwp/db/src/DB/QueryBuilder/Concerns/CRUD.php',
        'LearnDash\\Instructor_Role\\StellarWP\\DB\\QueryBuilder\\Concerns\\FromClause' => __DIR__ . '/..' . '/stellarwp/db/src/DB/QueryBuilder/Concerns/FromClause.php',
        'LearnDash\\Instructor_Role\\StellarWP\\DB\\QueryBuilder\\Concerns\\GroupByStatement' => __DIR__ . '/..' . '/stellarwp/db/src/DB/QueryBuilder/Concerns/GroupByStatement.php',
        'LearnDash\\Instructor_Role\\StellarWP\\DB\\QueryBuilder\\Concerns\\HavingClause' => __DIR__ . '/..' . '/stellarwp/db/src/DB/QueryBuilder/Concerns/HavingClause.php',
        'LearnDash\\Instructor_Role\\StellarWP\\DB\\QueryBuilder\\Concerns\\JoinClause' => __DIR__ . '/..' . '/stellarwp/db/src/DB/QueryBuilder/Concerns/JoinClause.php',
        'LearnDash\\Instructor_Role\\StellarWP\\DB\\QueryBuilder\\Concerns\\LimitStatement' => __DIR__ . '/..' . '/stellarwp/db/src/DB/QueryBuilder/Concerns/LimitStatement.php',
        'LearnDash\\Instructor_Role\\StellarWP\\DB\\QueryBuilder\\Concerns\\MetaQuery' => __DIR__ . '/..' . '/stellarwp/db/src/DB/QueryBuilder/Concerns/MetaQuery.php',
        'LearnDash\\Instructor_Role\\StellarWP\\DB\\QueryBuilder\\Concerns\\OffsetStatement' => __DIR__ . '/..' . '/stellarwp/db/src/DB/QueryBuilder/Concerns/OffsetStatement.php',
        'LearnDash\\Instructor_Role\\StellarWP\\DB\\QueryBuilder\\Concerns\\OrderByStatement' => __DIR__ . '/..' . '/stellarwp/db/src/DB/QueryBuilder/Concerns/OrderByStatement.php',
        'LearnDash\\Instructor_Role\\StellarWP\\DB\\QueryBuilder\\Concerns\\SelectStatement' => __DIR__ . '/..' . '/stellarwp/db/src/DB/QueryBuilder/Concerns/SelectStatement.php',
        'LearnDash\\Instructor_Role\\StellarWP\\DB\\QueryBuilder\\Concerns\\TablePrefix' => __DIR__ . '/..' . '/stellarwp/db/src/DB/QueryBuilder/Concerns/TablePrefix.php',
        'LearnDash\\Instructor_Role\\StellarWP\\DB\\QueryBuilder\\Concerns\\UnionOperator' => __DIR__ . '/..' . '/stellarwp/db/src/DB/QueryBuilder/Concerns/UnionOperator.php',
        'LearnDash\\Instructor_Role\\StellarWP\\DB\\QueryBuilder\\Concerns\\WhereClause' => __DIR__ . '/..' . '/stellarwp/db/src/DB/QueryBuilder/Concerns/WhereClause.php',
        'LearnDash\\Instructor_Role\\StellarWP\\DB\\QueryBuilder\\JoinQueryBuilder' => __DIR__ . '/..' . '/stellarwp/db/src/DB/QueryBuilder/JoinQueryBuilder.php',
        'LearnDash\\Instructor_Role\\StellarWP\\DB\\QueryBuilder\\QueryBuilder' => __DIR__ . '/..' . '/stellarwp/db/src/DB/QueryBuilder/QueryBuilder.php',
        'LearnDash\\Instructor_Role\\StellarWP\\DB\\QueryBuilder\\Types\\JoinType' => __DIR__ . '/..' . '/stellarwp/db/src/DB/QueryBuilder/Types/JoinType.php',
        'LearnDash\\Instructor_Role\\StellarWP\\DB\\QueryBuilder\\Types\\Math' => __DIR__ . '/..' . '/stellarwp/db/src/DB/QueryBuilder/Types/Math.php',
        'LearnDash\\Instructor_Role\\StellarWP\\DB\\QueryBuilder\\Types\\Operator' => __DIR__ . '/..' . '/stellarwp/db/src/DB/QueryBuilder/Types/Operator.php',
        'LearnDash\\Instructor_Role\\StellarWP\\DB\\QueryBuilder\\Types\\Type' => __DIR__ . '/..' . '/stellarwp/db/src/DB/QueryBuilder/Types/Type.php',
        'LearnDash\\Instructor_Role\\StellarWP\\DB\\QueryBuilder\\WhereQueryBuilder' => __DIR__ . '/..' . '/stellarwp/db/src/DB/QueryBuilder/WhereQueryBuilder.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit5b3b406b0c8b093372f4de300008eb3b::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit5b3b406b0c8b093372f4de300008eb3b::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit5b3b406b0c8b093372f4de300008eb3b::$classMap;

        }, null, ClassLoader::class);
    }
}
