<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'LearnDash\\Instructor_Role\\StellarWP\\DB\\' => array($vendorDir . '/stellarwp/db/src/DB'),
    'LearnDash\\Instructor_Role\\StellarWP\\Assets\\' => array($vendorDir . '/stellarwp/assets/src/Assets'),
    'LearnDash\\Instructor_Role\\StellarWP\\Arrays\\' => array($vendorDir . '/stellarwp/arrays/src/Arrays'),
);
