<?php

// autoload_real.php @generated by Composer

class ComposerAutoloaderInit5b3b406b0c8b093372f4de300008eb3b
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('LearnDash\Instructor_Role\Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \LearnDash\Instructor_Role\Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        require __DIR__ . '/platform_check.php';

        spl_autoload_register(array('ComposerAutoloaderInit5b3b406b0c8b093372f4de300008eb3b', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \LearnDash\Instructor_Role\Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('ComposerAutoloaderInit5b3b406b0c8b093372f4de300008eb3b', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        call_user_func(\LearnDash\Instructor_Role\Composer\Autoload\ComposerStaticInit5b3b406b0c8b093372f4de300008eb3b::getInitializer($loader));

        $loader->setClassMapAuthoritative(true);
        $loader->register(true);

        return $loader;
    }
}
