<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    '66aa6d00cd3bc97f26f570685acf7d51' => $vendorDir . '/myclabs/deep-copy/src/DeepCopy/deep_copy.php',
    '0d0eab5fc79213c2607e1ed7725d878c' => $vendorDir . '/mpdf/mpdf/src/functions.php',
);
