<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'LearnDash\\Certificate_Builder\\setasign\\Fpdi\\' => array($vendorDir . '/setasign/fpdi/src'),
    'LearnDash\\Certificate_Builder\\Psr\\Log\\' => array($vendorDir . '/psr/log/Psr/Log'),
    'LearnDash\\Certificate_Builder\\Psr\\Http\\Message\\' => array($vendorDir . '/psr/http-message/src'),
    'LearnDash\\Certificate_Builder\\Mpdf\\PsrLogAwareTrait\\' => array($vendorDir . '/mpdf/psr-log-aware-trait/src'),
    'LearnDash\\Certificate_Builder\\Mpdf\\PsrHttpMessageShim\\' => array($vendorDir . '/mpdf/psr-http-message-shim/src'),
    'LearnDash\\Certificate_Builder\\Mpdf\\' => array($vendorDir . '/mpdf/mpdf/src'),
    'LearnDash\\Certificate_Builder\\DeepCopy\\' => array($vendorDir . '/myclabs/deep-copy/src/DeepCopy'),
);
