<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'LearnDash\\Groups_Plus\\Composer\\InstalledVersions' => $vendorDir . '/composer/InstalledVersions.php',
    'LearnDash\\Groups_Plus\\Psr\\Container\\ContainerExceptionInterface' => $vendorDir . '/psr/container/src/ContainerExceptionInterface.php',
    'LearnDash\\Groups_Plus\\Psr\\Container\\ContainerInterface' => $vendorDir . '/psr/container/src/ContainerInterface.php',
    'LearnDash\\Groups_Plus\\Psr\\Container\\NotFoundExceptionInterface' => $vendorDir . '/psr/container/src/NotFoundExceptionInterface.php',
    'LearnDash\\Groups_Plus\\StellarWP\\AdminNotices\\Actions\\DisplayNoticesInAdmin' => $vendorDir . '/stellarwp/admin-notices/src/Actions/DisplayNoticesInAdmin.php',
    'LearnDash\\Groups_Plus\\StellarWP\\AdminNotices\\Actions\\EnqueueNoticesScriptsAndStyles' => $vendorDir . '/stellarwp/admin-notices/src/Actions/EnqueueNoticesScriptsAndStyles.php',
    'LearnDash\\Groups_Plus\\StellarWP\\AdminNotices\\Actions\\NoticeShouldRender' => $vendorDir . '/stellarwp/admin-notices/src/Actions/NoticeShouldRender.php',
    'LearnDash\\Groups_Plus\\StellarWP\\AdminNotices\\Actions\\RenderAdminNotice' => $vendorDir . '/stellarwp/admin-notices/src/Actions/RenderAdminNotice.php',
    'LearnDash\\Groups_Plus\\StellarWP\\AdminNotices\\AdminNotice' => $vendorDir . '/stellarwp/admin-notices/src/AdminNotice.php',
    'LearnDash\\Groups_Plus\\StellarWP\\AdminNotices\\AdminNotices' => $vendorDir . '/stellarwp/admin-notices/src/AdminNotices.php',
    'LearnDash\\Groups_Plus\\StellarWP\\AdminNotices\\Contracts\\NotificationsRegistrarInterface' => $vendorDir . '/stellarwp/admin-notices/src/Contracts/NotificationsRegistrarInterface.php',
    'LearnDash\\Groups_Plus\\StellarWP\\AdminNotices\\DataTransferObjects\\NoticeElementProperties' => $vendorDir . '/stellarwp/admin-notices/src/DataTransferObjects/NoticeElementProperties.php',
    'LearnDash\\Groups_Plus\\StellarWP\\AdminNotices\\Exceptions\\NotificationCollisionException' => $vendorDir . '/stellarwp/admin-notices/src/Exceptions/NotificationCollisionException.php',
    'LearnDash\\Groups_Plus\\StellarWP\\AdminNotices\\NotificationsRegistrar' => $vendorDir . '/stellarwp/admin-notices/src/NotificationsRegistrar.php',
    'LearnDash\\Groups_Plus\\StellarWP\\AdminNotices\\Traits\\HasNamespace' => $vendorDir . '/stellarwp/admin-notices/src/Traits/HasNamespace.php',
    'LearnDash\\Groups_Plus\\StellarWP\\AdminNotices\\ValueObjects\\NoticeLocation' => $vendorDir . '/stellarwp/admin-notices/src/ValueObjects/NoticeLocation.php',
    'LearnDash\\Groups_Plus\\StellarWP\\AdminNotices\\ValueObjects\\NoticeUrgency' => $vendorDir . '/stellarwp/admin-notices/src/ValueObjects/NoticeUrgency.php',
    'LearnDash\\Groups_Plus\\StellarWP\\AdminNotices\\ValueObjects\\ScreenCondition' => $vendorDir . '/stellarwp/admin-notices/src/ValueObjects/ScreenCondition.php',
    'LearnDash\\Groups_Plus\\StellarWP\\AdminNotices\\ValueObjects\\Script' => $vendorDir . '/stellarwp/admin-notices/src/ValueObjects/Script.php',
    'LearnDash\\Groups_Plus\\StellarWP\\AdminNotices\\ValueObjects\\Style' => $vendorDir . '/stellarwp/admin-notices/src/ValueObjects/Style.php',
    'LearnDash\\Groups_Plus\\StellarWP\\AdminNotices\\ValueObjects\\UserCapability' => $vendorDir . '/stellarwp/admin-notices/src/ValueObjects/UserCapability.php',
    'LearnDash\\Groups_Plus\\StellarWP\\Arrays\\Arr' => $vendorDir . '/stellarwp/arrays/src/Arrays/Arr.php',
    'LearnDash\\Groups_Plus\\StellarWP\\SuperGlobals\\SuperGlobals' => $vendorDir . '/stellarwp/superglobals/src/SuperGlobals/SuperGlobals.php',
    'LearnDash\\Groups_Plus\\lucatume\\DI52\\App' => $vendorDir . '/lucatume/di52/src/App.php',
    'LearnDash\\Groups_Plus\\lucatume\\DI52\\Builders\\BuilderInterface' => $vendorDir . '/lucatume/di52/src/Builders/BuilderInterface.php',
    'LearnDash\\Groups_Plus\\lucatume\\DI52\\Builders\\CallableBuilder' => $vendorDir . '/lucatume/di52/src/Builders/CallableBuilder.php',
    'LearnDash\\Groups_Plus\\lucatume\\DI52\\Builders\\ClassBuilder' => $vendorDir . '/lucatume/di52/src/Builders/ClassBuilder.php',
    'LearnDash\\Groups_Plus\\lucatume\\DI52\\Builders\\ClosureBuilder' => $vendorDir . '/lucatume/di52/src/Builders/ClosureBuilder.php',
    'LearnDash\\Groups_Plus\\lucatume\\DI52\\Builders\\Factory' => $vendorDir . '/lucatume/di52/src/Builders/Factory.php',
    'LearnDash\\Groups_Plus\\lucatume\\DI52\\Builders\\Parameter' => $vendorDir . '/lucatume/di52/src/Builders/Parameter.php',
    'LearnDash\\Groups_Plus\\lucatume\\DI52\\Builders\\ReinitializableBuilderInterface' => $vendorDir . '/lucatume/di52/src/Builders/ReinitializableBuilderInterface.php',
    'LearnDash\\Groups_Plus\\lucatume\\DI52\\Builders\\Resolver' => $vendorDir . '/lucatume/di52/src/Builders/Resolver.php',
    'LearnDash\\Groups_Plus\\lucatume\\DI52\\Builders\\ValueBuilder' => $vendorDir . '/lucatume/di52/src/Builders/ValueBuilder.php',
    'LearnDash\\Groups_Plus\\lucatume\\DI52\\Container' => $vendorDir . '/lucatume/di52/src/Container.php',
    'LearnDash\\Groups_Plus\\lucatume\\DI52\\ContainerException' => $vendorDir . '/lucatume/di52/src/ContainerException.php',
    'LearnDash\\Groups_Plus\\lucatume\\DI52\\NestedParseError' => $vendorDir . '/lucatume/di52/src/NestedParseError.php',
    'LearnDash\\Groups_Plus\\lucatume\\DI52\\NotFoundException' => $vendorDir . '/lucatume/di52/src/NotFoundException.php',
    'LearnDash\\Groups_Plus\\lucatume\\DI52\\ServiceProvider' => $vendorDir . '/lucatume/di52/src/ServiceProvider.php',
    'LearnDash_Groups_Plus_WP_Async_Request' => $vendorDir . '/deliciousbrains/wp-background-processing/classes/wp-async-request.php',
    'LearnDash_Groups_Plus_WP_Background_Process' => $vendorDir . '/deliciousbrains/wp-background-processing/classes/wp-background-process.php',
);
