<?php

// autoload_real.php @generated by Composer

class ComposerAutoloaderInitce3baaa1f7f6fa7ca683b262480e20b4
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('LearnDash\Groups_Plus\Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \LearnDash\Groups_Plus\Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        require __DIR__ . '/platform_check.php';

        spl_autoload_register(array('ComposerAutoloaderInitce3baaa1f7f6fa7ca683b262480e20b4', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \LearnDash\Groups_Plus\Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('ComposerAutoloaderInitce3baaa1f7f6fa7ca683b262480e20b4', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        call_user_func(\LearnDash\Groups_Plus\Composer\Autoload\ComposerStaticInitce3baaa1f7f6fa7ca683b262480e20b4::getInitializer($loader));

        $loader->setClassMapAuthoritative(true);
        $loader->register(true);

        return $loader;
    }
}
