<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'LearnDash\\Groups_Plus\\lucatume\\DI52\\' => array($vendorDir . '/lucatume/di52/src'),
    'LearnDash\\Groups_Plus\\StellarWP\\SuperGlobals\\' => array($vendorDir . '/stellarwp/superglobals/src/SuperGlobals'),
    'LearnDash\\Groups_Plus\\StellarWP\\Arrays\\' => array($vendorDir . '/stellarwp/arrays/src/Arrays'),
    'LearnDash\\Groups_Plus\\StellarWP\\AdminNotices\\' => array($vendorDir . '/stellarwp/admin-notices/src'),
    'LearnDash\\Groups_Plus\\Psr\\Container\\' => array($vendorDir . '/psr/container/src'),
);
