<?php

// autoload_static.php @generated by Composer

namespace LearnDash\Groups_Plus\Composer\Autoload;

class ComposerStaticInitce3baaa1f7f6fa7ca683b262480e20b4
{
    public static $prefixLengthsPsr4 = array (
        'L' =>
        array (
            'LearnDash\\Groups_Plus\\lucatume\\DI52\\' => 36,
            'LearnDash\\Groups_Plus\\StellarWP\\SuperGlobals\\' => 45,
            'LearnDash\\Groups_Plus\\StellarWP\\Arrays\\' => 39,
            'LearnDash\\Groups_Plus\\StellarWP\\AdminNotices\\' => 45,
            'LearnDash\\Groups_Plus\\Psr\\Container\\' => 36,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'LearnDash\\Groups_Plus\\lucatume\\DI52\\' =>
        array (
            0 => __DIR__ . '/..' . '/lucatume/di52/src',
        ),
        'LearnDash\\Groups_Plus\\StellarWP\\SuperGlobals\\' =>
        array (
            0 => __DIR__ . '/..' . '/stellarwp/superglobals/src/SuperGlobals',
        ),
        'LearnDash\\Groups_Plus\\StellarWP\\Arrays\\' =>
        array (
            0 => __DIR__ . '/..' . '/stellarwp/arrays/src/Arrays',
        ),
        'LearnDash\\Groups_Plus\\StellarWP\\AdminNotices\\' =>
        array (
            0 => __DIR__ . '/..' . '/stellarwp/admin-notices/src',
        ),
        'LearnDash\\Groups_Plus\\Psr\\Container\\' =>
        array (
            0 => __DIR__ . '/..' . '/psr/container/src',
        ),
    );

    public static $classMap = array (
        'LearnDash\\Groups_Plus\\Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'LearnDash\\Groups_Plus\\Psr\\Container\\ContainerExceptionInterface' => __DIR__ . '/..' . '/psr/container/src/ContainerExceptionInterface.php',
        'LearnDash\\Groups_Plus\\Psr\\Container\\ContainerInterface' => __DIR__ . '/..' . '/psr/container/src/ContainerInterface.php',
        'LearnDash\\Groups_Plus\\Psr\\Container\\NotFoundExceptionInterface' => __DIR__ . '/..' . '/psr/container/src/NotFoundExceptionInterface.php',
        'LearnDash\\Groups_Plus\\StellarWP\\AdminNotices\\Actions\\DisplayNoticesInAdmin' => __DIR__ . '/..' . '/stellarwp/admin-notices/src/Actions/DisplayNoticesInAdmin.php',
        'LearnDash\\Groups_Plus\\StellarWP\\AdminNotices\\Actions\\EnqueueNoticesScriptsAndStyles' => __DIR__ . '/..' . '/stellarwp/admin-notices/src/Actions/EnqueueNoticesScriptsAndStyles.php',
        'LearnDash\\Groups_Plus\\StellarWP\\AdminNotices\\Actions\\NoticeShouldRender' => __DIR__ . '/..' . '/stellarwp/admin-notices/src/Actions/NoticeShouldRender.php',
        'LearnDash\\Groups_Plus\\StellarWP\\AdminNotices\\Actions\\RenderAdminNotice' => __DIR__ . '/..' . '/stellarwp/admin-notices/src/Actions/RenderAdminNotice.php',
        'LearnDash\\Groups_Plus\\StellarWP\\AdminNotices\\AdminNotice' => __DIR__ . '/..' . '/stellarwp/admin-notices/src/AdminNotice.php',
        'LearnDash\\Groups_Plus\\StellarWP\\AdminNotices\\AdminNotices' => __DIR__ . '/..' . '/stellarwp/admin-notices/src/AdminNotices.php',
        'LearnDash\\Groups_Plus\\StellarWP\\AdminNotices\\Contracts\\NotificationsRegistrarInterface' => __DIR__ . '/..' . '/stellarwp/admin-notices/src/Contracts/NotificationsRegistrarInterface.php',
        'LearnDash\\Groups_Plus\\StellarWP\\AdminNotices\\DataTransferObjects\\NoticeElementProperties' => __DIR__ . '/..' . '/stellarwp/admin-notices/src/DataTransferObjects/NoticeElementProperties.php',
        'LearnDash\\Groups_Plus\\StellarWP\\AdminNotices\\Exceptions\\NotificationCollisionException' => __DIR__ . '/..' . '/stellarwp/admin-notices/src/Exceptions/NotificationCollisionException.php',
        'LearnDash\\Groups_Plus\\StellarWP\\AdminNotices\\NotificationsRegistrar' => __DIR__ . '/..' . '/stellarwp/admin-notices/src/NotificationsRegistrar.php',
        'LearnDash\\Groups_Plus\\StellarWP\\AdminNotices\\Traits\\HasNamespace' => __DIR__ . '/..' . '/stellarwp/admin-notices/src/Traits/HasNamespace.php',
        'LearnDash\\Groups_Plus\\StellarWP\\AdminNotices\\ValueObjects\\NoticeLocation' => __DIR__ . '/..' . '/stellarwp/admin-notices/src/ValueObjects/NoticeLocation.php',
        'LearnDash\\Groups_Plus\\StellarWP\\AdminNotices\\ValueObjects\\NoticeUrgency' => __DIR__ . '/..' . '/stellarwp/admin-notices/src/ValueObjects/NoticeUrgency.php',
        'LearnDash\\Groups_Plus\\StellarWP\\AdminNotices\\ValueObjects\\ScreenCondition' => __DIR__ . '/..' . '/stellarwp/admin-notices/src/ValueObjects/ScreenCondition.php',
        'LearnDash\\Groups_Plus\\StellarWP\\AdminNotices\\ValueObjects\\Script' => __DIR__ . '/..' . '/stellarwp/admin-notices/src/ValueObjects/Script.php',
        'LearnDash\\Groups_Plus\\StellarWP\\AdminNotices\\ValueObjects\\Style' => __DIR__ . '/..' . '/stellarwp/admin-notices/src/ValueObjects/Style.php',
        'LearnDash\\Groups_Plus\\StellarWP\\AdminNotices\\ValueObjects\\UserCapability' => __DIR__ . '/..' . '/stellarwp/admin-notices/src/ValueObjects/UserCapability.php',
        'LearnDash\\Groups_Plus\\StellarWP\\Arrays\\Arr' => __DIR__ . '/..' . '/stellarwp/arrays/src/Arrays/Arr.php',
        'LearnDash\\Groups_Plus\\StellarWP\\SuperGlobals\\SuperGlobals' => __DIR__ . '/..' . '/stellarwp/superglobals/src/SuperGlobals/SuperGlobals.php',
        'LearnDash\\Groups_Plus\\lucatume\\DI52\\App' => __DIR__ . '/..' . '/lucatume/di52/src/App.php',
        'LearnDash\\Groups_Plus\\lucatume\\DI52\\Builders\\BuilderInterface' => __DIR__ . '/..' . '/lucatume/di52/src/Builders/BuilderInterface.php',
        'LearnDash\\Groups_Plus\\lucatume\\DI52\\Builders\\CallableBuilder' => __DIR__ . '/..' . '/lucatume/di52/src/Builders/CallableBuilder.php',
        'LearnDash\\Groups_Plus\\lucatume\\DI52\\Builders\\ClassBuilder' => __DIR__ . '/..' . '/lucatume/di52/src/Builders/ClassBuilder.php',
        'LearnDash\\Groups_Plus\\lucatume\\DI52\\Builders\\ClosureBuilder' => __DIR__ . '/..' . '/lucatume/di52/src/Builders/ClosureBuilder.php',
        'LearnDash\\Groups_Plus\\lucatume\\DI52\\Builders\\Factory' => __DIR__ . '/..' . '/lucatume/di52/src/Builders/Factory.php',
        'LearnDash\\Groups_Plus\\lucatume\\DI52\\Builders\\Parameter' => __DIR__ . '/..' . '/lucatume/di52/src/Builders/Parameter.php',
        'LearnDash\\Groups_Plus\\lucatume\\DI52\\Builders\\ReinitializableBuilderInterface' => __DIR__ . '/..' . '/lucatume/di52/src/Builders/ReinitializableBuilderInterface.php',
        'LearnDash\\Groups_Plus\\lucatume\\DI52\\Builders\\Resolver' => __DIR__ . '/..' . '/lucatume/di52/src/Builders/Resolver.php',
        'LearnDash\\Groups_Plus\\lucatume\\DI52\\Builders\\ValueBuilder' => __DIR__ . '/..' . '/lucatume/di52/src/Builders/ValueBuilder.php',
        'LearnDash\\Groups_Plus\\lucatume\\DI52\\Container' => __DIR__ . '/..' . '/lucatume/di52/src/Container.php',
        'LearnDash\\Groups_Plus\\lucatume\\DI52\\ContainerException' => __DIR__ . '/..' . '/lucatume/di52/src/ContainerException.php',
        'LearnDash\\Groups_Plus\\lucatume\\DI52\\NestedParseError' => __DIR__ . '/..' . '/lucatume/di52/src/NestedParseError.php',
        'LearnDash\\Groups_Plus\\lucatume\\DI52\\NotFoundException' => __DIR__ . '/..' . '/lucatume/di52/src/NotFoundException.php',
        'LearnDash\\Groups_Plus\\lucatume\\DI52\\ServiceProvider' => __DIR__ . '/..' . '/lucatume/di52/src/ServiceProvider.php',
        'LearnDash_Groups_Plus_WP_Async_Request' => __DIR__ . '/..' . '/deliciousbrains/wp-background-processing/classes/wp-async-request.php',
        'LearnDash_Groups_Plus_WP_Background_Process' => __DIR__ . '/..' . '/deliciousbrains/wp-background-processing/classes/wp-background-process.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitce3baaa1f7f6fa7ca683b262480e20b4::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitce3baaa1f7f6fa7ca683b262480e20b4::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitce3baaa1f7f6fa7ca683b262480e20b4::$classMap;

        }, null, ClassLoader::class);
    }
}
